apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'

android {
    compileSdk 35

    namespace 'com.mckimquyen.opencal'
    defaultConfig {
        applicationId "com.mckimquyen.opencal"
        resourceConfigurations += ['ar', 'az', 'bn', 'bs', 'de', 'el', 'es', 'fa', 'fr', 'hi', 'hr', 'in', 'it', 'ja', 'mk', 'nb-rNO', 'pt-rBR', 'ru', 'tr', 'uk', 'vi', 'zh-rHK', 'zh-rTW']
        minSdkVersion 24
        targetSdkVersion 35
        versionCode 20250505
        versionName "2025.05.05"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    signingConfigs {
        release {
            storeFile file("keystore.jks")
            storePassword KS_PW
            keyAlias KS_ALIAS
            keyPassword KS_PW
        }
    }

    buildTypes {
        release {
            debuggable false
            minifyEnabled true
            shrinkResources true
            //used android.enableR8=true in gradle.properties
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.release
//            applicationIdSuffix ".release"
            // nhớ check APPLICATION_ID trong manifest
            buildConfigField "String", "ADMOB_BANNER_ID", "\"ca-app-pub-3612191981543807/4627557404\""
            buildConfigField "String", "ADMOB_INTERSTITIAL_ID", "\"ca-app-pub-3612191981543807/4059747044\""
            buildConfigField "String", "ADMOB_APP_OPEN_ID", "\"ca-app-pub-3612191981543807/7338622864\""
        }
        debug {
            minifyEnabled false
            //used android.enableR8=true in gradle.properties
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
//            applicationIdSuffix ".debug"
            buildConfigField "String", "ADMOB_BANNER_ID", "\"ca-app-pub-3940256099942544/6300978111\""
            buildConfigField "String", "ADMOB_INTERSTITIAL_ID", "\"ca-app-pub-3940256099942544/1033173712\""
            buildConfigField "String", "ADMOB_APP_OPEN_ID", "\"ca-app-pub-3940256099942544/9257395921\""
        }
    }

    viewBinding {
        enabled = true
    }

    buildFeatures {
        viewBinding = true
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = 17
    }

    android.applicationVariants.configureEach { variant ->
        variant.outputs.configureEach {
            outputFileName = defaultConfig.applicationId + buildType.name + "_" + defaultConfig.versionName + "_" + defaultConfig.versionCode + ".apk"
        }
    }

    flavorDimensions.add("type")
    productFlavors {

        dev {
            dimension "type"
            buildConfigField("String", "FLAVOR_buildEnv", '"dev"')
//            resValue "string", "app_name", "Base DEV"

//            resValue("string", "SDK_KEY", "e75FnQfS9XTTqM1Kne69U7PW_MBgAnGQTFvtwVVui6kRPKs5L7ws9twr5IQWwVfzPKZ5pF2IfDa7lguMgGlCyt")
//            resValue("string", "BANNER", "86cdc9050561f316")
//            resValue("string", "INTER", "4e8de0b36750ea6c")
//            resValue("string", "EnableAdInter", "true")
//            resValue("string", "EnableAdBanner", "true")
        }

        production {
            dimension "type"
            buildConfigField("String", "FLAVOR_buildEnv", '"prod"')
//            resValue "string", "app_name", "Base"

//            resValue("string", "SDK_KEY", "e75FnQfS9XTTqM1Kne69U7PW_MBgAnGQTFvtwVVui6kRPKs5L7ws9twr5IQWwVfzPKZ5pF2IfDa7lguMgGlCyt")
//            resValue("string", "BANNER", "86cdc9050561f316")
//            resValue("string", "INTER", "4e8de0b36750ea6c")
//            resValue("string", "EnableAdInter", "true")
//            resValue("string", "EnableAdBanner", "true")
        }

    }
}

dependencies {
    api fileTree(dir: "libs", include: ["*.jar"])
    api 'androidx.core:core-ktx:1.16.0'
    api 'androidx.appcompat:appcompat:1.7.0'
    api 'androidx.preference:preference-ktx:1.2.1'
    api 'androidx.constraintlayout:constraintlayout:2.2.1'
    api 'com.google.android.material:material:1.12.0'
    api "androidx.lifecycle:lifecycle-viewmodel-ktx:2.8.7"
    api 'com.github.hannesa2:AndroidSlidingUpPanel:4.5.0'
    api 'androidx.preference:preference-ktx:1.2.1'
    api 'com.google.code.gson:gson:2.11.0'
//    api 'com.applovin:applovin-sdk:13.0.1'
    implementation("com.google.android.gms:play-services-ads:24.2.0")
    implementation("com.google.android.play:review:2.0.2")
    implementation("com.google.android.play:review-ktx:2.0.2")
    debugImplementation 'com.squareup.leakcanary:leakcanary-android:2.14'
}
